### ISSUE TITLE
Can't figure it out how to run unoconv

### ISSUE THREAD

**Issue by laclaw-ga** [unoconv/unoconv#348]
I have tried reinstalling the libreoffice and unoconv several times, and the following error persists:

```
Traceback (most recent call last):
  File "/usr/local/bin/unoconv", line 1330, in <module>
    from com.sun.star.document.UpdateDocMode import QUIET_UPDATE
  File "/Applications/LibreOffice.app/Contents/Resources/uno.py", line 339, in _uno_import
    raise uno_import_exc
  File "/Applications/LibreOffice.app/Contents/Resources/uno.py", line 265, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
  File "/Applications/LibreOffice.app/Contents/Resources/uno.py", line 265, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
  File "/Applications/LibreOffice.app/Contents/Resources/uno.py", line 265, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
  File "/Applications/LibreOffice.app/Contents/Resources/uno.py", line 265, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
  File "/Applications/LibreOffice.app/Contents/Resources/uno.py", line 265, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
ImportError: No module named 'com' (or 'com.sun.star.document.UpdateDocMode.QUIET_UPDATE' is unknown)
```

Any ideias why, and how to fix?

**Comment by regebro** [comment]
How did you run it? Is this still a problem?
