### ISSUE TITLE
feedback: LibreOffice 5.3.1.2 on Mac OS X 10.12.4 (Sierra)

### ISSUE THREAD

**Issue by sjborley** [unoconv/unoconv#391]
On running the following I get a error, and a request for feedback

steven$ unoconv -f csv  myfile.ods 
unoconv: Cannot find a suitable pyuno library and python binary combination in /Applications/LibreOffice.app/Contents
ERROR: No module named uno

unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
       http://github.com/dagwieers/unoconv/issues

This is what I found...
=== LibreOffice 5.3.1.2 on Mac OS X 10.12.4 (Sierra)
uno:: /Applications/LibreOffice.app/Contents//MacOS/uno
programs:: not present as a directory or a symlink
soffice.bin:: /Applications/LibreOffice.app/Contents/MacOS/soffice
python.bin:: not present
python::  /Applications/LibreOffice.app/Contents/Resources/python
pyuno.so:: /Applications/LibreOffice.app/Contents/Frameworks/libpyuno.so
pyuno.dylib::  /Applications/LibreOffice.app/Contents/Frameworks/libpyuno.dylib
python library /Applications/LibreOffice.app/Contents//Frameworks/LibreOfficePython.framework
python-core:: not present

/Applications/LibreOffice.app/Contents/Resources/python --version
Python 3.5.3

Note the unoconv I'm using was cloned from git today

**Comment by harrywynn** [comment]
@sjborley try using an older version of Libre Office.  This one worked for me: https://libreoffice.en.uptodown.com/mac/download/40075

I've also installed unoconv through Homebrew, if that helps.

**Comment by SainteCelery** [comment]
I'm having the same issue on the same system. I, also, installed both LibreOffice and unoconv with homebrew.

Installing a version of LibreOffice two entire point versions old seems like a bad idea. What other solutions exist? Is there a fix for this bug in progress?

**Comment by regebro** [comment]
All our integration tests fail on Mac OS lately, something has happened there. I don't have OS X available, and I don't personally need OS X support, so I'm looking for help here, somebody that are willing to try to debug this and figure out what fails.

**Comment by yugonline** [comment]
Thank you @harrywynn I got it to work with your suggested changes

P.S: Anyone knows what this warning is about?
`CoreAnimation: warning, deleted thread with uncommitted CATransaction; set CA_DEBUG_TRANSACTIONS=1 in environment to log backtraces, or set CA_ASSERT_MAIN_THREAD_TRANSACTIONS=1 to abort when an implicit transaction isn't created on a main thread.`

It seems like it is a warning thrown by LibreOffice. But still.

**Comment by munichman2008** [comment]
I found out you can instead use the latest version of LibreOffice and simply convert your documents using the command-line options. It seems to me an easier and more straight-forward way of converting documents. Follow the instructions here: https://ask.libreoffice.org/en/question/12084/how-to-convert-documents-to-pdf-on-osx/

**Comment by regebro** [comment]
Yes, but that's not practical if you convert a lot of documents, as you will have to start Libreoffice every time you convert.

But absolutely, if you only convert a document here and there, that's probably a better solution.

**Comment by SainteCelery** [comment]
I [queried about alternative options on stackexchange](https://apple.stackexchange.com/questions/290682/how-do-i-batch-convert-hundreds-of-clarisworks-documents-to-a-modern-format) and found a solution in [the libmwaw tools available on sourceforge](https://sourceforge.net/projects/libmwaw/), specifically the mwawOSX app.

**Comment by janssen** [comment]
Well, the merge helped some, but it's still not fixed.  I just installed from the master branch, and got this:

```
$ unoconv -vvv --help
Traceback (most recent call last):
  File "/opt/CBMX/bin/unoconv", line 4, in <module>
    __import__('pkg_resources').run_script('unoconv==0.8.2', 'unoconv')
  File "/opt/CBMX/lib/python2.7/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/CBMX/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1509, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'unoconv'
$
```

In other words, it's still not finding the right Python.  Might be because the script still mentions OOoFramework?  Line 118.

**Comment by janssen** [comment]
Thought I'd try using the LibreOffice python to install it:

```
$ /Applications/LibreOffice.app/Contents/Resources/python setup.py install
/Applications/LibreOffice.app/Contents/Resources/python setup.py install
Traceback (most recent call last):
  File "/Applications/LibreOffice.app/Contents/Frameworks/LibreOfficePython.framework/Versions/3.5/lib/python3.5/distutils/sysconfig.py", line 419, in _init_posix
    parse_makefile(filename, g)
  File "/Applications/LibreOffice.app/Contents/Frameworks/LibreOfficePython.framework/Versions/3.5/lib/python3.5/distutils/sysconfig.py", line 288, in parse_makefile
    fp = TextFile(fn, strip_comments=1, skip_blanks=1, join_lines=1, errors="surrogateescape")
  File "/Applications/LibreOffice.app/Contents/Frameworks/LibreOfficePython.framework/Versions/3.5/lib/python3.5/distutils/text_file.py", line 100, in __init__
    self.open(filename)
  File "/Applications/LibreOffice.app/Contents/Frameworks/LibreOfficePython.framework/Versions/3.5/lib/python3.5/distutils/text_file.py", line 115, in open
    self.file = io.open(self.filename, 'r', errors=self.errors)
FileNotFoundError: [Errno 2] No such file or directory: '/Applications/LibreOffice.app/Contents/Frameworks/LibreOfficePython.framework/lib/python3.5/config-3.5m/Makefile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 117, in <module>
    zip_safe = False
  File "/Applications/LibreOffice.app/Contents/Frameworks/LibreOfficePython.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 121, in setup
    dist.parse_config_files()
  File "/Applications/LibreOffice.app/Contents/Frameworks/LibreOfficePython.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 386, in parse_config_files
    filenames = self.find_config_files()
  File "/Applications/LibreOffice.app/Contents/Frameworks/LibreOfficePython.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 338, in find_config_files
    check_environ()
  File "/Applications/LibreOffice.app/Contents/Frameworks/LibreOfficePython.framework/Versions/3.5/lib/python3.5/distutils/util.py", line 179, in check_environ
    os.environ['PLAT'] = get_platform()
  File "/Applications/LibreOffice.app/Contents/Frameworks/LibreOfficePython.framework/Versions/3.5/lib/python3.5/distutils/util.py", line 103, in get_platform
    distutils.sysconfig.get_config_vars(),
  File "/Applications/LibreOffice.app/Contents/Frameworks/LibreOfficePython.framework/Versions/3.5/lib/python3.5/distutils/sysconfig.py", line 482, in get_config_vars
    func()
  File "/Applications/LibreOffice.app/Contents/Frameworks/LibreOfficePython.framework/Versions/3.5/lib/python3.5/distutils/sysconfig.py", line 425, in _init_posix
    raise DistutilsPlatformError(my_msg)
distutils.errors.DistutilsPlatformError: invalid Python installation: unable to open /Applications/LibreOffice.app/Contents/Frameworks/LibreOfficePython.framework/lib/python3.5/config-3.5m/Makefile (No such file or directory)
$
```

**Comment by EvgeniyGorbachev** [comment]
A good instruction for installation: https://docs.moodle.org/35/en/Universal_Office_Converter_(unoconv)#Installing_unoconv_on_OS_X

**Comment by TranBaVinhSon** [comment]
Is there any solution for this problem?

**Comment by devinea** [comment]
@TranBaVinhSon 

Try this 

##### Step1. Download and install LibreOffice v6.2.* for Mac ##### 
[Download](https://downloadarchive.documentfoundation.org/libreoffice/old/6.1.5.2/mac/x86_64/LibreOffice_6.2.2.1_MacOS_x86-64.dmg).
 
##### Step2. Install unoconv #####
Recommended to install unoconv from master branch https://github.com/unoconv/unoconv, this assummes `/usr/local/bin` is part of your `PATH`
```bash
curl -o ~/unoconv https://raw.githubusercontent.com/unoconv/unoconv/63f6b13b6b027b9d552b445dacc8316d7a276043/unoconv
chmod +x ~/unoconv
ln -s ~/unoconv /usr/local/bin/unoconv
```
Note: At the time of testing, `brew` installs release v0.8.2, dated Dec 2017 which is not compatible with LibreOffice v6.1

##### Step3. Check unoconv is working ##### 
```
$ unoconv --version
unoconv 0.8.2
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/darwin
python 3.5.6 (default, Feb 27 2019, 13:28:28) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
LibreOffice 6.1.5.2
```
##### Step4. Check LibreOffice is working #####  
```
$ /Applications/LibreOffice.app/Contents/MacOS/soffice --version
LibreOffice 6.1.5.2 90f8dcf33c87b3705e78202e3df5142b201bd805
```

**Comment by TranBaVinhSon** [comment]
@devinea Thank you man, you save my life 🥇

**Comment by DavidAyliffe** [comment]
This is slightly confusing.

Does unoconv 0.8.2 work with LibreOffice 6.1.5.2 on mac OS (e.g. 10.14.5)?

Thanks

**Comment by devinea** [comment]
@DavidAyliffe yes unoconv seems to work with Libreoffice 6.x fine on macOS based on instructions above. 
I haven't tested extensively on macOS as I mostly use unoconv on Linux.
