### ISSUE TITLE
Cannot find a suitable office installation on your system on Heroku-16 (based on Ubuntu 16.04)

### ISSUE THREAD

**Issue by jjalan** [unoconv/unoconv#457]
Env: Heroku-16 stack, based on Ubuntu 16.04

I am trying to install from stretch main.

After installation, it says
```
unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
       http://github.com/dagwieers/unoconv/issues
```

After I set UNO_PATH
`export UNO_PATH='/app/.apt/usr/lib/libreoffice`

I get
```
unoconv: Cannot find a suitable pyuno library and python binary combination in /app/.apt/usr/lib/libreoffice
ERROR: No module named 'uno'

unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
       http://github.com/dagwieers/unoconv/issues

```
Here are values for other paths:
`$PYTHONPATH`: Empty
`$PATH`: `/app/.heroku/node/bin:/app/.heroku/yarn/bin:/app/.heroku/bin:/app/.jdk/bin:/app/.apt/usr/bin:/usr/local/bin:/usr/bin:/bin:/app/bin:/app/node_modules/.bin`
`PYTHONPATH`: Empty
`LD_LIBRARY_PATH`: `/app/.jdk/jre/lib/amd64/server:/app/.apt/usr/lib/x86_64-linux-gnu:/app/.apt/usr/lib/i386-linux-gnu:/app/.apt/usr/lib:`

**Comment by jjalan** [comment]
I also checked that when unoconv is installed via apt, pyuno etc. installed as can be seen from following logs

```
-----> Fetching .debs for unoconv
       Reading package lists...
       Building dependency tree...
       The following additional packages will be installed:
         adwaita-icon-theme at-spi2-core coinor-libcbc3 coinor-libcgl1 coinor-libclp1
         coinor-libcoinmp1v5 coinor-libcoinutils3v5 coinor-libosi1v5
         dconf-gsettings-backend dconf-service dictionaries-common emacsen-common
         fonts-liberation fonts-opensymbol gcc-6-base glib-networking
         glib-networking-common glib-networking-services gsettings-desktop-schemas
         gstreamer1.0-plugins-base gtk-update-icon-cache hunspell-en-us iso-codes
         krb5-multidev libabw-0.1-1 libalgorithm-diff-xs-perl libatk-bridge2.0-0
         libatspi2.0-0 libblas-common libblas3 libboost-date-time1.62.0
         libboost-filesystem1.58.0 libboost-filesystem1.62.0 libboost-iostreams1.62.0
         libboost-system1.58.0 libboost-system1.62.0 libcapnp-0.5.3 libcdparanoia0
         libcdr-0.1-1 libclucene-contribs1v5 libclucene-core1v5 libcmis-0.5-5v5
         libcolamd2 libcolord2 libdbus-glib-1-2 libdconf1 libdrm-amdgpu1
         libdrm-common libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libdrm2
         libe-book-0.1-1 libegl1-mesa libeot0 libepoxy0 libetonyek-0.1-1
         libexttextcat-2.0-0 libexttextcat-data libfile-fcntllock-perl
         libfreehand-0.1-1 libgail-common libgail18 libgbm1 libgcc1 libgfortran3
         libgl1-mesa-dri libgl1-mesa-glx libglapi-mesa libglew2.0 libglib2.0-0
         libglib2.0-bin libglib2.0-dev libgltf-0.0-0v5 libglu1-mesa libgnutls-dane0
         libgnutls-openssl27 libgnutls28-dev libgnutls30 libgnutlsxx28
         libgssapi-krb5-2 libgssrpc4 libgstreamer-plugins-base1.0-0 libgstreamer1.0-0
         libgtk-3-0 libgtk-3-bin libgtk-3-common libgtk2.0-0 libgtk2.0-bin
         libharfbuzz-icu0 libhunspell-1.4-0 libhyphen0 libicu57 libjpeg62-turbo
         libjson-glib-1.0-0 libjson-glib-1.0-common libk5crypto3 libkadm5clnt-mit11
         libkadm5srv-mit11 libkrb5-3 libkrb5-dev libkrb5support0 liblangtag-common
         liblangtag1 liblapack3 libllvm6.0 libmhash2 libmirclient9 libmircommon7
         libmircore1 libmirprotobuf3 libmspub-0.1-1 libmwaw-0.3-3 libmythes-1.2-0
         libneon27-gnutls libnspr4 libnss3 libnss3-nssdb libodfgen-0.1-1 libogg0
         libopus0 liborc-0.4-0 liborcus-0.11-0 libpagemaker-0.0-0 libpciaccess0
         libperl5.24 libpng16-16 libprotobuf-lite9v5 libproxy1v5 libpython3.5
         libpython3.5-minimal libpython3.5-stdlib libraptor2-0 librasqal3 librdf0
         libreadline7 libreoffice-avmedia-backend-gstreamer libreoffice-base-core
         libreoffice-calc libreoffice-common libreoffice-core libreoffice-draw
         libreoffice-impress libreoffice-math libreoffice-style-galaxy
         libreoffice-writer librest-0.7-0 librevenge-0.0-0 libsensors4
         libsoup-gnome2.4-1 libsoup2.4-1 libssl1.1 libsuitesparseconfig4 libtasn1-6
         libtasn1-6-dev libtext-iconv-perl libtheora0 libtxc-dxtn-s2tc libunbound2
         libvisio-0.1-1 libvisual-0.4-0 libvorbis0a libvorbisenc2 libwayland-client0
         libwayland-cursor0 libwayland-egl1-mesa libwayland-server0 libwpd-0.10-10
         libwpg-0.3-3 libwps-0.4-4 libx11-xcb1 libxcb-dri2-0 libxcb-dri3-0
         libxcb-glx0 libxcb-present0 libxcb-sync1 libxcb-xfixes0 libxcb1 libxcb1-dev
         libxkbcommon0 libxshmfence1 libxtst6 libxxf86vm1 libyajl2 lp-solve perl
         perl-base perl-modules-5.24 python3-uno python3.5 python3.5-minimal
         uno-libs3 ure xkb-data
       Suggested packages:
         ispell | aspell | hunspell wordlist gvfs hunspell openoffice.org-hunspell
         | openoffice.org-core isoquery krb5-doc colord glew-utils libglib2.0-doc
         dns-root-data gnutls-doc gnutls-bin krb5-user libvisual-0.4-plugins
         gstreamer1.0-tools opus-tools pciutils raptor2-utils rasqal-utils
         librdf-storage-postgresql librdf-storage-mysql librdf-storage-sqlite
         librdf-storage-virtuoso redland-utils libreoffice-base ocl-icd-libopencl1
         libreoffice-style-breeze libreoffice-style-hicontrast
         libreoffice-style-oxygen libreoffice-style-sifr libreoffice-style-tango
         bluez fonts-crosextra-caladea fonts-crosextra-carlito libreoffice-gcj
         libreoffice-java-common default-jre | openjdk-8-jre | openjdk-7-jre
         | openjdk-6-jre | gcj-jre | sun-java5-jre | sun-java6-jre | java5-runtime
         | jre lm-sensors libxcb-doc perl-doc libterm-readline-gnu-perl
         | libterm-readline-perl-perl python3.5-venv python3.5-doc binfmt-support
         java5-runtime
       Recommended packages:
         libtasn1-doc
       The following packages will be REMOVED:
         libgnutls-dev libperl5.22 perl-modules-5.22
       The following NEW packages will be installed:
         adwaita-icon-theme at-spi2-core coinor-libcbc3 coinor-libcgl1 coinor-libclp1
         coinor-libcoinmp1v5 coinor-libcoinutils3v5 coinor-libosi1v5
         dconf-gsettings-backend dconf-service dictionaries-common emacsen-common
         fonts-liberation fonts-opensymbol glib-networking glib-networking-common
         glib-networking-services gsettings-desktop-schemas gstreamer1.0-plugins-base
         gtk-update-icon-cache hunspell-en-us iso-codes libabw-0.1-1
         libatk-bridge2.0-0 libatspi2.0-0 libblas-common libblas3
         libboost-date-time1.62.0 libboost-filesystem1.58.0 libboost-filesystem1.62.0
         libboost-iostreams1.62.0 libboost-system1.58.0 libboost-system1.62.0
         libcapnp-0.5.3 libcdparanoia0 libcdr-0.1-1 libclucene-contribs1v5
         libclucene-core1v5 libcmis-0.5-5v5 libcolamd2 libcolord2 libdbus-glib-1-2
         libdconf1 libdrm-amdgpu1 libdrm-common libdrm-intel1 libdrm-nouveau2
         libdrm-radeon1 libdrm2 libe-book-0.1-1 libegl1-mesa libeot0 libepoxy0
         libetonyek-0.1-1 libexttextcat-2.0-0 libexttextcat-data libfreehand-0.1-1
         libgail-common libgail18 libgbm1 libgfortran3 libgl1-mesa-dri
         libgl1-mesa-glx libglapi-mesa libglew2.0 libgltf-0.0-0v5 libglu1-mesa
         libgnutls-dane0 libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 libgtk-3-0
         libgtk-3-bin libgtk-3-common libharfbuzz-icu0 libhunspell-1.4-0 libhyphen0
         libicu57 libjpeg62-turbo libjson-glib-1.0-0 libjson-glib-1.0-common
         libkadm5clnt-mit11 libkadm5srv-mit11 liblangtag-common liblangtag1
         liblapack3 libllvm6.0 libmhash2 libmirclient9 libmircommon7 libmircore1
         libmirprotobuf3 libmspub-0.1-1 libmwaw-0.3-3 libmythes-1.2-0
         libneon27-gnutls libnspr4 libnss3 libnss3-nssdb libodfgen-0.1-1 libogg0
         libopus0 liborc-0.4-0 liborcus-0.11-0 libpagemaker-0.0-0 libpciaccess0
         libperl5.24 libpng16-16 libprotobuf-lite9v5 libproxy1v5 libpython3.5
         libraptor2-0 librasqal3 librdf0 libreadline7
         libreoffice-avmedia-backend-gstreamer libreoffice-base-core libreoffice-calc
         libreoffice-common libreoffice-core libreoffice-draw libreoffice-impress
         libreoffice-math libreoffice-style-galaxy libreoffice-writer librest-0.7-0
         librevenge-0.0-0 libsensors4 libsoup-gnome2.4-1 libsoup2.4-1 libssl1.1
         libsuitesparseconfig4 libtext-iconv-perl libtheora0 libtxc-dxtn-s2tc
         libunbound2 libvisio-0.1-1 libvisual-0.4-0 libvorbis0a libvorbisenc2
         libwayland-client0 libwayland-cursor0 libwayland-egl1-mesa
         libwayland-server0 libwpd-0.10-10 libwpg-0.3-3 libwps-0.4-4 libx11-xcb1
         libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0 libxcb-sync1
         libxcb-xfixes0 libxkbcommon0 libxshmfence1 libxtst6 libxxf86vm1 libyajl2
         lp-solve perl-modules-5.24 python3-uno uno-libs3 unoconv ure xkb-data
       The following packages will be upgraded:
         gcc-6-base krb5-multidev libalgorithm-diff-xs-perl libfile-fcntllock-perl
         libgcc1 libglib2.0-0 libglib2.0-bin libglib2.0-dev libgnutls-openssl27
         libgnutls28-dev libgnutls30 libgnutlsxx28 libgssapi-krb5-2 libgssrpc4
         libgtk2.0-0 libgtk2.0-bin libk5crypto3 libkrb5-3 libkrb5-dev libkrb5support0
         libpython3.5-minimal libpython3.5-stdlib libtasn1-6 libtasn1-6-dev libxcb1
         libxcb1-dev perl perl-base python3.5 python3.5-minimal
       30 upgraded, 165 newly installed, 3 to remove and 469 not upgraded.
       Need to get 0 B/183 MB of archives.
       After this operation, 719 MB of additional disk space will be used.
       WARNING: The following packages cannot be authenticated!
         libfile-fcntllock-perl libalgorithm-diff-xs-perl perl-modules-5.24
         libperl5.24 perl perl-base gcc-6-base libgcc1 libgnutls28-dev libgnutlsxx28
         libgnutls-openssl27 libtasn1-6-dev libtasn1-6 libgnutls30 libunbound2
         libgnutls-dane0 fonts-opensymbol libreoffice-style-galaxy uno-libs3 ure
         libreoffice-common libboost-date-time1.62.0 libclucene-core1v5
         libclucene-contribs1v5 libcmis-0.5-5v5 libglib2.0-dev libglib2.0-bin
         libglib2.0-0 libdbus-glib-1-2 libdconf1 libeot0 libexttextcat-data
         libexttextcat-2.0-0 libx11-xcb1 libxcb1-dev libxcb1 libxcb-dri2-0
         libxcb-dri3-0 libxcb-glx0 libxcb-present0 libxcb-sync1 libxshmfence1
W: --force-yes is deprecated, use one of the options starting with --allow instead.
W: --force-yes is deprecated, use one of the options starting with --allow instead.
         libxxf86vm1 libpciaccess0 libsensors4 libglew2.0 libgltf-0.0-0v5 libicu57
         libharfbuzz-icu0 libhunspell-1.4-0 libhyphen0 libjpeg62-turbo
         liblangtag-common liblangtag1 libmythes-1.2-0 libkrb5-dev krb5-multidev
         libk5crypto3 libgssapi-krb5-2 libkrb5-3 libkrb5support0 libgssrpc4
         libkadm5srv-mit11 libkadm5clnt-mit11 libneon27-gnutls librevenge-0.0-0
         libodfgen-0.1-1 libpng16-16 libyajl2 libraptor2-0 librasqal3 librdf0
         libreoffice-core libgstreamer1.0-0 liborc-0.4-0 iso-codes
         libgstreamer-plugins-base1.0-0 dconf-service dconf-gsettings-backend
         libgtk-3-common libatspi2.0-0 libatk-bridge2.0-0 libcolord2 libepoxy0
         libjson-glib-1.0-common libjson-glib-1.0-0 libproxy1v5
         glib-networking-common glib-networking-services gsettings-desktop-schemas
         glib-networking libsoup2.4-1 libsoup-gnome2.4-1 librest-0.7-0
         libwayland-client0 libwayland-cursor0 libwayland-server0 xkb-data
         libxkbcommon0 libxcb-xfixes0 libgtk2.0-bin libgtk2.0-0 gtk-update-icon-cache
         adwaita-icon-theme libgtk-3-0 libreoffice-avmedia-backend-gstreamer
         libreoffice-base-core libsuitesparseconfig4 libcolamd2 lp-solve libgfortran3
         libblas-common libblas3 liblapack3 coinor-libcoinutils3v5 coinor-libosi1v5
         coinor-libclp1 coinor-libcgl1 coinor-libcbc3 libboost-system1.62.0
         libboost-filesystem1.62.0 libboost-iostreams1.62.0 libetonyek-0.1-1
         libmwaw-0.3-3 liborcus-0.11-0 libwps-0.4-4 libreoffice-calc libcdr-0.1-1
         libfreehand-0.1-1 libmspub-0.1-1 libpagemaker-0.0-0 libvisio-0.1-1
         libwpd-0.10-10 libwpg-0.3-3 libreoffice-draw libreoffice-impress
         libreoffice-math libabw-0.1-1 libe-book-0.1-1 libreoffice-writer libssl1.1
         python3.5 libpython3.5-stdlib python3.5-minimal libpython3.5-minimal
         libreadline7 libxtst6 at-spi2-core libtext-iconv-perl dictionaries-common
         fonts-liberation libopus0 libtheora0 libvisual-0.4-0 libvorbis0a
         libvorbisenc2 gstreamer1.0-plugins-base hunspell-en-us libgail18
         libgail-common libgtk-3-bin libpython3.5 python3-uno libtxc-dxtn-s2tc
       Download complete and in download only mode
-----> Installing adwaita-icon-theme_3.22.0-1+deb9u1_all.deb
-----> Installing at-spi2-core_2.22.0-6+deb9u1_amd64.deb
-----> Installing coinor-libcbc3_2.8.12-1+b2_amd64.deb
-----> Installing coinor-libcgl1_0.58.9-1+b1_amd64.deb
-----> Installing coinor-libclp1_1.15.10-3+b1_amd64.deb
-----> Installing coinor-libcoinmp1v5_1.7.6+dfsg1-2build1_amd64.deb
-----> Installing coinor-libcoinutils3v5_2.9.15-4_amd64.deb
-----> Installing coinor-libosi1v5_0.106.9-2+b1_amd64.deb
-----> Installing dconf-gsettings-backend_0.26.0-2+b1_amd64.deb
-----> Installing dconf-service_0.26.0-2+b1_amd64.deb
-----> Installing dictionaries-common_1.27.2_all.deb
-----> Installing emacsen-common_2.0.8_all.deb
-----> Installing fonts-liberation_1%3a1.07.4-2_all.deb
-----> Installing fonts-opensymbol_2%3a102.7+LibO5.2.7-1+deb9u3_all.deb
-----> Installing gcc-6-base_6.3.0-18+deb9u1_amd64.deb
-----> Installing glib-networking_2.50.0-1+b1_amd64.deb
-----> Installing glib-networking-common_2.50.0-1_all.deb
-----> Installing glib-networking-services_2.50.0-1+b1_amd64.deb
-----> Installing gsettings-desktop-schemas_3.22.0-1_all.deb
-----> Installing gstreamer1.0-plugins-base_1.10.4-1_amd64.deb
-----> Installing gtk-update-icon-cache_3.22.11-1_amd64.deb
-----> Installing hunspell-en-us_20070829-7_all.deb
-----> Installing iso-codes_3.75-1_all.deb
-----> Installing krb5-multidev_1.15-1+deb9u1_amd64.deb
-----> Installing libabw-0.1-1_0.1.1-4_amd64.deb
-----> Installing libalgorithm-diff-xs-perl_0.04-4+b2_amd64.deb
-----> Installing libatk-bridge2.0-0_2.22.0-2_amd64.deb
-----> Installing libatspi2.0-0_2.22.0-6+deb9u1_amd64.deb
-----> Installing libblas3_3.7.0-2_amd64.deb
-----> Installing libblas-common_3.7.0-2_amd64.deb
-----> Installing libboost-date-time1.62.0_1.62.0+dfsg-4_amd64.deb
-----> Installing libboost-filesystem1.58.0_1.58.0+dfsg-5ubuntu3.1_amd64.deb
-----> Installing libboost-filesystem1.62.0_1.62.0+dfsg-4_amd64.deb
-----> Installing libboost-iostreams1.62.0_1.62.0+dfsg-4_amd64.deb
-----> Installing libboost-system1.58.0_1.58.0+dfsg-5ubuntu3.1_amd64.deb
-----> Installing libboost-system1.62.0_1.62.0+dfsg-4_amd64.deb
-----> Installing libcapnp-0.5.3_0.5.3-2ubuntu1_amd64.deb
-----> Installing libcdparanoia0_3.10.2+debian-11_amd64.deb
-----> Installing libcdr-0.1-1_0.1.3-3+b1_amd64.deb
-----> Installing libclucene-contribs1v5_2.3.3.4+dfsg-1_amd64.deb
-----> Installing libclucene-core1v5_2.3.3.4+dfsg-1_amd64.deb
-----> Installing libcmis-0.5-5v5_0.5.1+git20160603-3+b1_amd64.deb
-----> Installing libcolamd2_1%3a4.5.4-1_amd64.deb
-----> Installing libcolord2_1.3.3-2_amd64.deb
-----> Installing libdbus-glib-1-2_0.108-2_amd64.deb
-----> Installing libdconf1_0.26.0-2+b1_amd64.deb
-----> Installing libdrm2_2.4.91-2~16.04.1_amd64.deb
-----> Installing libdrm-amdgpu1_2.4.91-2~16.04.1_amd64.deb
-----> Installing libdrm-common_2.4.91-2~16.04.1_all.deb
-----> Installing libdrm-intel1_2.4.91-2~16.04.1_amd64.deb
-----> Installing libdrm-nouveau2_2.4.91-2~16.04.1_amd64.deb
-----> Installing libdrm-radeon1_2.4.91-2~16.04.1_amd64.deb
-----> Installing libe-book-0.1-1_0.1.2-4_amd64.deb
-----> Installing libegl1-mesa_18.0.5-0ubuntu0~16.04.1_amd64.deb
-----> Installing libeot0_0.01-4+b1_amd64.deb
-----> Installing libepoxy0_1.3.1-2_amd64.deb
-----> Installing libetonyek-0.1-1_0.1.6-5_amd64.deb
-----> Installing libexttextcat-2.0-0_3.4.4-2+b1_amd64.deb
-----> Installing libexttextcat-data_3.4.4-2_all.deb
-----> Installing libfile-fcntllock-perl_0.22-3+b2_amd64.deb
-----> Installing libfreehand-0.1-1_0.1.1-2_amd64.deb
-----> Installing libgail18_2.24.31-2_amd64.deb
-----> Installing libgail-common_2.24.31-2_amd64.deb
-----> Installing libgbm1_18.0.5-0ubuntu0~16.04.1_amd64.deb
-----> Installing libgcc1_1%3a6.3.0-18+deb9u1_amd64.deb
-----> Installing libgfortran3_6.3.0-18+deb9u1_amd64.deb
-----> Installing libgl1-mesa-dri_18.0.5-0ubuntu0~16.04.1_amd64.deb
-----> Installing libgl1-mesa-glx_18.0.5-0ubuntu0~16.04.1_amd64.deb
-----> Installing libglapi-mesa_18.0.5-0ubuntu0~16.04.1_amd64.deb
-----> Installing libglew2.0_2.0.0-3+b1_amd64.deb
-----> Installing libglib2.0-0_2.50.3-2_amd64.deb
-----> Installing libglib2.0-bin_2.50.3-2_amd64.deb
-----> Installing libglib2.0-dev_2.50.3-2_amd64.deb
-----> Installing libgltf-0.0-0v5_0.0.2-5_amd64.deb
-----> Installing libglu1-mesa_9.0.0-2.1_amd64.deb
-----> Installing libgnutls28-dev_3.5.8-5+deb9u3_amd64.deb
-----> Installing libgnutls30_3.5.8-5+deb9u3_amd64.deb
-----> Installing libgnutls-dane0_3.5.8-5+deb9u3_amd64.deb
-----> Installing libgnutls-openssl27_3.5.8-5+deb9u3_amd64.deb
-----> Installing libgnutlsxx28_3.5.8-5+deb9u3_amd64.deb
-----> Installing libgssapi-krb5-2_1.15-1+deb9u1_amd64.deb
-----> Installing libgssrpc4_1.15-1+deb9u1_amd64.deb
-----> Installing libgstreamer1.0-0_1.10.4-1_amd64.deb
-----> Installing libgstreamer-plugins-base1.0-0_1.10.4-1_amd64.deb
-----> Installing libgtk2.0-0_2.24.31-2_amd64.deb
-----> Installing libgtk2.0-bin_2.24.31-2_amd64.deb
-----> Installing libgtk-3-0_3.22.11-1_amd64.deb
-----> Installing libgtk-3-bin_3.22.11-1_amd64.deb
-----> Installing libgtk-3-common_3.22.11-1_all.deb
-----> Installing libharfbuzz-icu0_1.4.2-1_amd64.deb
-----> Installing libhunspell-1.4-0_1.4.1-2+b2_amd64.deb
-----> Installing libhyphen0_2.8.8-5_amd64.deb
-----> Installing libicu57_57.1-6+deb9u1_amd64.deb
-----> Installing libjpeg62-turbo_1%3a1.5.1-2_amd64.deb
-----> Installing libjson-glib-1.0-0_1.2.6-1_amd64.deb
-----> Installing libjson-glib-1.0-common_1.2.6-1_all.deb
-----> Installing libk5crypto3_1.15-1+deb9u1_amd64.deb
-----> Installing libkadm5clnt-mit11_1.15-1+deb9u1_amd64.deb
-----> Installing libkadm5srv-mit11_1.15-1+deb9u1_amd64.deb
-----> Installing libkrb5-3_1.15-1+deb9u1_amd64.deb
-----> Installing libkrb5-dev_1.15-1+deb9u1_amd64.deb
-----> Installing libkrb5support0_1.15-1+deb9u1_amd64.deb
-----> Installing liblangtag1_0.6.2-1_amd64.deb
-----> Installing liblangtag-common_0.6.2-1_all.deb
-----> Installing liblapack3_3.7.0-2_amd64.deb
-----> Installing libllvm6.0_1%3a6.0-1ubuntu2~16.04.1_amd64.deb
-----> Installing libmhash2_0.9.9.9-7_amd64.deb
-----> Installing libmirclient9_0.26.3+16.04.20170605-0ubuntu1.1_amd64.deb
-----> Installing libmircommon7_0.26.3+16.04.20170605-0ubuntu1.1_amd64.deb
-----> Installing libmircore1_0.26.3+16.04.20170605-0ubuntu1.1_amd64.deb
-----> Installing libmirprotobuf3_0.26.3+16.04.20170605-0ubuntu1.1_amd64.deb
-----> Installing libmspub-0.1-1_0.1.2-4+b1_amd64.deb
-----> Installing libmwaw-0.3-3_0.3.9-2_amd64.deb
-----> Installing libmythes-1.2-0_2%3a1.2.4-3_amd64.deb
-----> Installing libneon27-gnutls_0.30.2-2_amd64.deb
-----> Installing libnspr4_2%3a4.13.1-0ubuntu0.16.04.1_amd64.deb
-----> Installing libnss3_2%3a3.28.4-0ubuntu0.16.04.3_amd64.deb
-----> Installing libnss3-nssdb_2%3a3.28.4-0ubuntu0.16.04.3_all.deb
-----> Installing libodfgen-0.1-1_0.1.6-2_amd64.deb
-----> Installing libogg0_1.3.2-1_amd64.deb
-----> Installing libopus0_1.2~alpha2-1_amd64.deb
-----> Installing liborc-0.4-0_1%3a0.4.26-2_amd64.deb
-----> Installing liborcus-0.11-0_0.11.2-3+b1_amd64.deb
-----> Installing libpagemaker-0.0-0_0.0.3-2_amd64.deb
-----> Installing libpciaccess0_0.13.4-1+b2_amd64.deb
-----> Installing libperl5.24_5.24.1-3+deb9u2_amd64.deb
-----> Installing libpng16-16_1.6.28-1_amd64.deb
-----> Installing libprotobuf-lite9v5_2.6.1-1.3_amd64.deb
-----> Installing libproxy1v5_0.4.14-2_amd64.deb
-----> Installing libpython3.5_3.5.3-1_amd64.deb
-----> Installing libpython3.5-minimal_3.5.3-1_amd64.deb
-----> Installing libpython3.5-stdlib_3.5.3-1_amd64.deb
-----> Installing libraptor2-0_2.0.14-1+b1_amd64.deb
-----> Installing librasqal3_0.9.32-1+b1_amd64.deb
-----> Installing librdf0_1.0.17-1.1_amd64.deb
-----> Installing libreadline7_7.0-3_amd64.deb
-----> Installing libreoffice-avmedia-backend-gstreamer_1%3a5.2.7-1+deb9u3_amd64.deb
-----> Installing libreoffice-base-core_1%3a5.2.7-1+deb9u3_amd64.deb
-----> Installing libreoffice-calc_1%3a5.2.7-1+deb9u3_amd64.deb
-----> Installing libreoffice-common_1%3a5.2.7-1+deb9u3_all.deb
-----> Installing libreoffice-core_1%3a5.2.7-1+deb9u3_amd64.deb
-----> Installing libreoffice-draw_1%3a5.2.7-1+deb9u3_amd64.deb
-----> Installing libreoffice-impress_1%3a5.2.7-1+deb9u3_amd64.deb
-----> Installing libreoffice-math_1%3a5.2.7-1+deb9u3_amd64.deb
-----> Installing libreoffice-style-galaxy_1%3a5.2.7-1+deb9u3_all.deb
-----> Installing libreoffice-writer_1%3a5.2.7-1+deb9u3_amd64.deb
-----> Installing librest-0.7-0_0.8.0-2_amd64.deb
-----> Installing librevenge-0.0-0_0.0.4-6_amd64.deb
-----> Installing libsensors4_1%3a3.4.0-4_amd64.deb
-----> Installing libsoup2.4-1_2.56.0-2+deb9u1_amd64.deb
-----> Installing libsoup-gnome2.4-1_2.56.0-2+deb9u1_amd64.deb
-----> Installing libssl1.1_1.1.0f-3+deb9u1_amd64.deb
-----> Installing libsuitesparseconfig4_1%3a4.5.4-1_amd64.deb
-----> Installing libtasn1-6_4.10-1.1+deb9u1_amd64.deb
-----> Installing libtasn1-6-dev_4.10-1.1+deb9u1_amd64.deb
-----> Installing libtext-iconv-perl_1.7-5+b4_amd64.deb
-----> Installing libtheora0_1.1.1+dfsg.1-14+b1_amd64.deb
-----> Installing libtxc-dxtn-s2tc_1.0+git20151227-2_amd64.deb
-----> Installing libunbound2_1.6.0-3+deb9u1_amd64.deb
-----> Installing libvisio-0.1-1_0.1.5-4+b1_amd64.deb
-----> Installing libvisual-0.4-0_0.4.0-10_amd64.deb
-----> Installing libvorbis0a_1.3.5-4_amd64.deb
-----> Installing libvorbisenc2_1.3.5-4_amd64.deb
-----> Installing libwayland-client0_1.12.0-1_amd64.deb
-----> Installing libwayland-cursor0_1.12.0-1_amd64.deb
-----> Installing libwayland-egl1-mesa_18.0.5-0ubuntu0~16.04.1_amd64.deb
-----> Installing libwayland-server0_1.12.0-1_amd64.deb
-----> Installing libwpd-0.10-10_0.10.1-5+deb9u1_amd64.deb
-----> Installing libwpg-0.3-3_0.3.1-3_amd64.deb
-----> Installing libwps-0.4-4_0.4.5-1_amd64.deb
-----> Installing libx11-xcb1_2%3a1.6.4-3_amd64.deb
-----> Installing libxcb1_1.12-1_amd64.deb
-----> Installing libxcb1-dev_1.12-1_amd64.deb
-----> Installing libxcb-dri2-0_1.12-1_amd64.deb
-----> Installing libxcb-dri3-0_1.12-1_amd64.deb
-----> Installing libxcb-glx0_1.12-1_amd64.deb
-----> Installing libxcb-present0_1.12-1_amd64.deb
-----> Installing libxcb-sync1_1.12-1_amd64.deb
-----> Installing libxcb-xfixes0_1.12-1_amd64.deb
-----> Installing libxkbcommon0_0.7.1-2~deb9u1_amd64.deb
-----> Installing libxshmfence1_1.2-1+b2_amd64.deb
-----> Installing libxtst6_2%3a1.2.3-1_amd64.deb
-----> Installing libxxf86vm1_1%3a1.1.4-1+b2_amd64.deb
-----> Installing libyajl2_2.1.0-2+b3_amd64.deb
-----> Installing lp-solve_5.5.0.15-4+b1_amd64.deb
-----> Installing perl_5.24.1-3+deb9u2_amd64.deb
-----> Installing perl-base_5.24.1-3+deb9u2_amd64.deb
-----> Installing perl-modules-5.24_5.24.1-3+deb9u2_all.deb
-----> Installing python3.5_3.5.3-1_amd64.deb
-----> Installing python3.5-minimal_3.5.3-1_amd64.deb
-----> Installing python3-uno_1%3a5.2.7-1+deb9u3_amd64.deb
-----> Installing unoconv_0.7-1.1_all.deb
-----> Installing uno-libs3_5.2.7-1+deb9u3_amd64.deb
-----> Installing ure_5.2.7-1+deb9u3_amd64.deb
-----> Installing xkb-data_2.19-1+deb9u1_all.deb
-----> Writing profile script
-----> Rewrite package-config files
```

On system at `/app/.apt/usr/lib/python3/dist-packages`, I see two files `uno.py	unohelper.py` are present.

**Comment by regebro** [comment]
I've noticed that when these issues arise, the solution is to run unoconv with the python executable that comes with the Libreoffice installation you want to use. Like so:

    UNOPATH=/path/to/Libreoffice /path/to/Libreoffice/program/python /usr/bin/unoconv ....

Yes, that's fairly annoying.

**Comment by regebro** [comment]
I'm keeping this open since it's on the first page, although strictly it's a duplicate of #49.

**Comment by sita-prajapati-bullhorn** [comment]
Getting following error 
`Traceback (most recent call last):
  File "/app/.apt/usr/bin/unoconv", line 1236, in <module>
    from com.sun.star.document.UpdateDocMode import QUIET_UPDATE
  File "/app/.apt/usr/lib/python3/dist-packages/uno.py", line 342, in _uno_import
    raise uno_import_exc
  File "/app/.apt/usr/lib/python3/dist-packages/uno.py", line 268, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
  File "/app/.apt/usr/lib/python3/dist-packages/uno.py", line 268, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
  File "/app/.apt/usr/lib/python3/dist-packages/uno.py", line 268, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
  File "/app/.apt/usr/lib/python3/dist-packages/uno.py", line 268, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
  File "/app/.apt/usr/lib/python3/dist-packages/uno.py", line 268, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
ImportError: No module named 'com' (or 'com.sun.star.document.UpdateDocMode.QUIET_UPDATE' is unknown)`

**Comment by regebro** [comment]
How did you start unoconv?

**Comment by sita-prajapati-bullhorn** [comment]
Setup unoconv in heroku using guidelines mentioned in this link https://github.com/josduj/heroku-buildpack-unoconv

Commad that I'm using `unoconv -f pdf "https://tr-releaseorg.s3.amazonaws.com/00D1N000002C4IX/00P1N00000wq89oUAA/CVArnaudAlexander.docx"`

**Comment by regebro** [comment]
I've noticed that when these issues arise, the solution is to run unoconv with the python executable that comes with the Libreoffice installation you want to use. Like so:

UNOPATH=/path/to/Libreoffice /path/to/Libreoffice/program/python /usr/bin/unoconv ....

**Comment by sita-prajapati-bullhorn** [comment]
Getting following error while looking at unoconv version
![image](https://user-images.githubusercontent.com/43531009/61786780-170c8000-ae2c-11e9-9a0a-61b96a805e8a.png)

**Comment by regebro** [comment]
So, you did NOT run unoconv with the python executable that comes with the Libreoffice installation you want to use. Please do so.

**Comment by sita-prajapati-bullhorn** [comment]
Libreoffice doesn't have python. 
![image](https://user-images.githubusercontent.com/43531009/61788640-32798a00-ae30-11e9-849d-48627bd117a6.png)

**Comment by regebro** [comment]
"Even libreoffice throwing this error"

Then your Libreoffice installation is broken, so you need to reinstall it.

**Comment by KrzysiekJ** [comment]
The problem seems to occur also on a generic Ubuntu 16.04.6. Installing `libreoffice-script-provider-python` and `libreoffice` doesn’t place a standalone Python in `/usr/lib/libreoffice/program`.
