### ISSUE TITLE
UNO IllegalArgument during import phase: Source file cannot be read. URL seems to be an unsupported one.

### ISSUE THREAD

**Issue by ousia** [unoconv/unoconv#47]
If I try to convert http://www.users.dircon.co.uk/~hancock/antioch2.doc, I get an error:

```
$ unoconv -f pdf antioch2.doc 
unoconv: UnoException during conversion in <class '__main__.com.sun.star.lang.IllegalArgumentException'>: URL seems to be an unsupported one.
Traceback (most recent call last):
  File "/usr/bin/unoconv", line 801, in <module>
    main()
  File "/usr/bin/unoconv", line 780, in main
    convertor.convert(inputfn)
  File "/usr/bin/unoconv", line 690, in convert
    error("ERROR: The provided document cannot be converted to the desired format. (code: %s)" % e.ErrCode)
  File "/usr/lib/python2.7/site-packages/uno.py", line 318, in _uno_struct__getattr__
    return __builtin__.getattr(self.__dict__["value"],name)
AttributeError: ErrCode
```

Many thanks for your help,

Pablo

**Comment by liuguodong1019** [comment]
谁可以告诉我，这个问题最后是怎么解决的
