### ISSUE TITLE
AttributeError: ErrCode

### ISSUE THREAD

**Issue by nadermx** [unoconv/unoconv#499]
I'm on `ubuntu 18`, running a virtual enviroment with `python 3.6.7`

When I try and run this command `unoconv -vvv -f html /home/john/tocapetown.pdf -o tocapetown.html` I get this error 
```
Verbosity set to level 3
Using office base path: /usr/lib/libreoffice
Using office binary path: /usr/lib/libreoffice/program
DEBUG: Connection type: socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ComponentContext
Input file: /home/john/tocapetown.pdf
Selected output format: HTML Document (OpenOffice.org Writer) [.html]
Selected office filter: HTML (StarWriter)
Used doctype: document
Output file: file:///home/john/tocapetown.html
Traceback (most recent call last):
  File "/home/john/.virtualenvs/pdf3/bin/unoconv", line 1118, in convert
    document.storeToURL(outputurl, tuple(outputprops) )
uno.IOException: SfxBaseModel::impl_store <file:///home/john/tocapetown.html> failed: 0xc10

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/john/.virtualenvs/pdf3/bin/unoconv", line 1389, in <module>
    main()
  File "/home/john/.virtualenvs/pdf3/bin/unoconv", line 1305, in main
    convertor.convert(inputfn)
  File "/home/john/.virtualenvs/pdf3/bin/unoconv", line 1120, in convert
    raise UnoException("Unable to store document to %s (ErrCode %d)\n\nProperties: %s" % (outputurl, e.ErrCode, outputprops), None)
  File "/usr/lib/python3/dist-packages/uno.py", line 507, in _uno_struct__getattr__
    return getattr(self.__dict__["value"], name)
AttributeError: ErrCode

```

**Comment by Wanderish** [comment]
Found any workarounds or solutions, @nadermx ?

**Comment by nadermx** [comment]
It seems unoconv is unable to convert from pdf to html
