### ISSUE TITLE
the error when using unoconv

### ISSUE THREAD

**Issue by Jianfenman** [unoconv/unoconv#502]
when use the script: unoconv  -f pdf test1.docx
give these error:
Traceback (most recent call last):
  File "/ifs7/B2C_USER/manjianfen/anaconda3/bin/unoconv", line 4, in <module>
    __import__('pkg_resources').run_script('unoconv==0.8.2', 'unoconv')
  File "/ifs7/B2C_USER/manjianfen/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/ifs7/B2C_USER/manjianfen/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1432, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/unoconv' not found in metadata at '/ifs7/B2C_USER/manjianfen/anaconda3/lib/python3.7/site-packages/unoconv-0.8.2.dist-info'

Thanks

**Comment by m1waterman88** [comment]
It appears you're trying to use a Python interpreter outside of the one delivered with the office installation. Try using the provided interpreter and see what happens.

**Comment by m1waterman88** [comment]
Closing issue. There is insufficient information, and there hasn't been a response. If conda is using a virtual environment, it's likely the issue lies between condas available packages and what it can communicate with on the system, including packages necessary for unoconv to run.
