### ISSUE TITLE
Unoconv fails to read from stdin

### ISSUE THREAD

**Issue by nie7321** [unoconv/unoconv#518]
Unoconv doesn't seem to be able to read HTML from stdin anymore -- just gives an error. There was some discussion [here](https://github.com/unoconv/unoconv/pull/203#issuecomment-278542158), but that's a closed issue.

This doesn't appear to be a problem when converting binary data from stdin.

```
echo "foo" | /usr/bin/unoconv --format=txt --stdout --stdin
Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1275, in <module>
    main()
  File "/usr/bin/unoconv", line 1187, in main
    convertor.convert(inputfn)
  File "/usr/bin/unoconv", line 892, in convert
    inputStream.initialize((uno.ByteSequence(inputfn),))
  File "/usr/lib/python3/dist-packages/uno.py", line 282, in __init__
    raise TypeError("Expected bytes object or ByteSequence, got %s instead." % type(value))
TypeError: Expected bytes object or ByteSequence, got <class 'str'> instead.
```

Here's version info:

```
# unoconv --version && dpkg -l | grep uno
unoconv 0.7
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux
python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0]
LibreOffice 6.1.5.2
ii  python3-uno                           1:6.1.5-3+deb10u5            amd64        Python-UNO bridge
ii  uno-libs3                             6.1.5-3+deb10u5              amd64        LibreOffice UNO runtime environment -- public shared libraries
ii  unoconv                               0.7-1.1                      all          converter between LibreOffice document formats
```

**Comment by kticka** [comment]
I got problems here too. :) It would be very useful if this would work. Now I need temp file to convert xlsx export to pdf. I could just pass xlsx buffer instead.

```
cat full.xlsx | unoconv --output=out.pdf --doctype=spreadsheet --stdin
func=xmlSecCheckVersionExt:file=xmlsec.c:line=188:obj=unknown:subj=unknown:error=19:invalid version:mode=abi compatible;expected minor version=2;real minor version=2;expected subminor version=25;real subminor version=26
Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1404, in <module>
    main()
  File "/usr/bin/unoconv", line 1316, in main
    convertor.convert(inputfn)
  File "/usr/bin/unoconv", line 1115, in convert
    if os.path.exists(inputfn):
  File "/usr/lib64/python3.6/genericpath.py", line 19, in exists
    os.stat(path)
ValueError: stat: embedded null character in path
```

```
unoconv --version
unoconv 0.9.0
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux
python 3.6.8 (default, Apr 16 2020, 01:36:27)
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
LibreOffice 6.0.6.1
```

**Comment by m1waterman88** [comment]
I tested both of the provided commands.

`echo "foo" | /usr/bin/unoconv --format=txt --stdout --stdin`
`cat full.xlsx | unoconv --output=out.pdf --doctype=spreadsheet --stdin`

Each was tested with the latest unoconv version in the Ubuntu repos (0.7) and the latest version in pip (0.9.0). Both commands were successful with the pip version, and both failed with the universe version.

@kticka, I suspect it's your LibreOffice version. Here's my output:

```
unoconv 0.9.0
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux
python 3.8.6 (default, Sep 25 2020, 09:36:53) 
[GCC 10.2.0]
LibreOffice 7.0.2.2
```

**Comment by regebro** [comment]
We had problems with stdin/stdout under Python 3. Perhaps it's that?

The rewrite: https://github.com/unoconv/unoserver/, which only supports Python 3 should work better in that case.
