### ISSUE TITLE
LooseVersion deprecated

### ISSUE THREAD

**Issue by testote** [unoconv/unoconv#593]
distutils libraries has been replaced for other libraries.  Thus,

`ImportError: cannot import name 'LooseVersion' from 'distutils' (/usr/lib/python3.10/distutils/__init__.py)`

disutils'.LooseVersion has been replaced by packaging.version but it is not compatible. Thus,

```
Traceback (most recent call last):
  File "/usr/bin/unoconv", line 848, in connect
    unocontext = resolver.resolve("uno:%s" % op.connection)
uno.com.sun.star.connection.NoConnectException: Connector : couldn't connect to socket (Connection refused) /build/libreoffice-fresh/src/libreoffice-7.3.1.3/io/source/connector/connector.cxx:117

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1436, in <module>
    main()
  File "/usr/bin/unoconv", line 1350, in main
    convertor = Convertor()
  File "/usr/bin/unoconv", line 827, in __init__
    unocontext = self.connect(resolver)
  File "/usr/bin/unoconv", line 860, in connect
    if product.ooName not in ('LibreOffice', 'LOdev') or LooseVersion(product.ooSetupVersion) <= LooseVersion('3.3'):
TypeError: 'module' object is not callable
```

We may loose some retrocompatibility but it works if:
19 `from distutils.version import LooseVersion`
and
870 `...  or LooseVersion(product.ooSetupVersion) <= LooseVersion('3.3') ...`
are removed.

Cheers.

**Comment by rcrath** [comment]
I hope this can be fixed properly while unoconver/unoserver are not feature equivalent yet (I need wildcards for e.g.)

**Comment by Yelinz** [comment]
duplicate from https://github.com/unoconv/unoconv/issues/593

**Comment by pft** [comment]
It looks like we can replace distutils.version.LooseVersion with packaging.version.Version

**Comment by pft** [comment]
I tried replacing the module, but this poses problems for e.g. windows users, where the provided Python installation does not include `packaging`, or people using earlier versions of Python. 

LooseVersion is used to check whether the LO version is younger than 3.3. So I created this [PR](https://github.com/unoconv/unoconv/pull/621), with a custom comparison function not relying on any module.
