### ISSUE TITLE
Convert .cdr to .svg failed

### ISSUE THREAD

**Issue by Rombersoft** [unoconv/unoconv#612]
On the Debian 11 desktop, it converts well but on the Debian docker I get such the error:

`# unoconv -f svg -T 30 test.cdr
Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1037, in convert
    document.storeToURL(outputurl, tuple(outputprops) )
uno.com.sun.star.io.IOException: SfxBaseModel::impl_store <file:///mnt/test.svg> failed: 0xc10(Error Area:Io Class:Write Code:16) at ./sfx2/source/doc/sfxbasemodel.cxx:3207 at ./sfx2/source/doc/sfxbasemodel.cxx:1783

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1282, in <module>
    main()
  File "/usr/bin/unoconv", line 1198, in main
    convertor.convert(inputfn)
  File "/usr/bin/unoconv", line 1039, in convert
    raise UnoException("Unable to store document to %s (ErrCode %d)\n\nProperties: %s" % (outputurl, e.ErrCode, outputprops), None)
                                                                                                     ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/uno.py", line 507, in _uno_struct__getattr__
    return getattr(self.__dict__["value"], name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: ErrCode`

But it converts .cdr to .jpg well.
The LibreOffice version on docker is 7.4.7.2, and on Desktop Debian 11 is 7.0.4.2.

What can be the cause of this error?

**Comment by Kahz3l** [comment]
I have the same problem:
```
root@hrconvert2-b65d4c8db-7jdrm:/tmp# python3 /usr/bin/unoconv -vvv -f docx /DATA/HRConvert2/Test-PDF-Formular.pdf -o /tmp/Test.docx
/usr/bin/unoconv:19: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.version import LooseVersion
Verbosity set to level 3
Using office base path: /usr/lib/libreoffice
Using office binary path: /usr/lib/libreoffice/program
DEBUG: Connection type: socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ComponentContext
Input file: /DATA/HRConvert2/Test-PDF-Formular.pdf
Selected output format: Microsoft Office Open XML [.docx]
Selected office filter: Office Open XML Text
Used doctype: document
Output file: file:///DATA/HRConvert2/Test-PDF-Formular.docx
Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1037, in convert
    document.storeToURL(outputurl, tuple(outputprops) )
uno.com.sun.star.io.IOException: SfxBaseModel::impl_store <file:///DATA/HRConvert2/Test-PDF-Formular.docx> failed: 0xc10(Error Area:Io Class:Write Code:16) at ./sfx2/source/doc/sfxbasemodel.cxx:3207 at ./sfx2/source
/doc/sfxbasemodel.cxx:1783

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1282, in <module>
    main()
  File "/usr/bin/unoconv", line 1198, in main
    convertor.convert(inputfn)
  File "/usr/bin/unoconv", line 1039, in convert
    raise UnoException("Unable to store document to %s (ErrCode %d)\n\nProperties: %s" % (outputurl, e.ErrCode, outputprops), None)
                                                                                                     ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/uno.py", line 507, in _uno_struct__getattr__
    return getattr(self.__dict__["value"], name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: ErrCode
```

```
root@hrconvert2-b65d4c8db-7jdrm:/tmp# python3 /usr/bin/unoconv --version
/usr/bin/unoconv:19: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.version import LooseVersion
unoconv 0.7
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux
python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
LibreOffice 7.4.7.2
```

changing permissions for the folders does not work.
